/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOZPTPDF
#define ROOZPTPDF

#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooRealVar.h>
#include <RooAbsCategory.h>

class RooZPtPdf : public RooAbsPdf {
	public:
		RooZPtPdf() {} ; 
		RooZPtPdf(const char *name, const char *title,
			RooAbsReal & _zpt,
			RooAbsReal & _p1,
			RooAbsReal & _p2,
			RooAbsReal & _p3,
			RooAbsReal & _p4,
			RooAbsReal & _p5);
		RooZPtPdf(const RooZPtPdf & other, const char * name = 0) ;
		inline virtual TObject* clone(const char* newname) const { return new RooZPtPdf(*this, newname); }
		inline virtual ~RooZPtPdf() {}
		Double_t evaluate() const;
		Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
		Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
	protected:
		RooRealProxy zpt;
		RooRealProxy p1;
		RooRealProxy p2;
		RooRealProxy p3;
		RooRealProxy p4;
		RooRealProxy p5;
	private:
		ClassDef(RooZPtPdf,2);
};

#endif
